export const fortunes = [
  "The weather will betray your outfit choice. Believe it.",
  "Your phone battery will die at the worst moment 📱. Today only.",
  "Console.log is your spirit animal. Consider yourself warned.",
  "Today is a two-coffee kind of day ☕☕. This is fine 🔥.",
  "Naming things will haunt you forever. Good luck!",
  "The bug was a feature all along. Tested in production.",
  "The weather will betray your outfit choice. Today only.",
  "The universe approves your snack choice. Believe it.",
  "The universe approves your snack choice. This is fine 🔥.",
  "The bug was a feature all along. Today only.",
  "You will meet someone who asks 'So what do you do?' Today only.",
  "Someone will say 'Let's circle back' in a meeting.",
  "Naming things will haunt you forever. Today only.",
  "Your pizza will arrive with extra cheese 🧀. Today only.",
  "Aliens are debugging the universe 👽. Tested in production.",
  "The bug was a feature all along. Good luck!",
  "You will find fries at the bottom of the bag 🍟. Tested in production.",
  "The stars say 'try turning it off and on again'. Try again later.",
  "Git will ask you to resolve 100 conflicts today.",
  "You will laugh at your own joke today. Consider yourself warned.",
  "Your fridge holds secrets beyond yogurt. Today only.",
  "Someone will say 'Let's circle back' in a meeting. Today only.",
  "Deploy on Friday, what could go wrong? Consider yourself warned.",
  "404 fortune not found. Today only.",
  "Today is a two-coffee kind of day ☕☕. Today only.",
  "You will debug in one try today. This is fine 🔥.",
  "StackOverflow is your second brain. This is fine 🔥.",
  "Naming things will haunt you forever. Try again later.",
  "StackOverflow is your second brain. Believe it.",
  "The universe approves your snack choice. Try again later.",
  "Your next commit message will be 'fix stuff'. This is fine 🔥.",
  "Tomorrow’s bug will be today’s feature. This is fine 🔥.",
  "WiFi will betray you when you need it most. Try again later.",
  "Tomorrow’s bug will be today’s feature. Consider yourself warned.",
  "You will debug in one try today.",
  "You will debug in one try today. Good luck!",
  "StackOverflow is your second brain. Consider yourself warned.",
  "Your next commit message will be 'fix stuff'. Tested in production.",
  "A cat will walk across your keyboard 🐈.",
  "The elevator will stop on every floor today. Today only.",
  "Naming things will haunt you forever. Believe it.",
  "The bug was a feature all along. This is fine 🔥.",
  "The bug was a feature all along. Try again later.",
  "The bug was a feature all along. Consider yourself warned.",
  "Your code is bug-free… until QA sees it. Try again later.",
  "WiFi will betray you when you need it most. Good luck!",
  "WiFi will betray you when you need it most. Tested in production.",
  "You will meet someone who asks 'So what do you do?'",
  "The weather will betray your outfit choice. Try again later.",
  "Your fridge holds secrets beyond yogurt.",
  "The stars say 'try turning it off and on again'. Good luck!",
  "The elevator will stop on every floor today. Consider yourself warned.",
  "You will meet someone who asks 'So what do you do?' Try again later.",
  "Tomorrow’s bug will be today’s feature. Try again later.",
  "Your pizza will arrive with extra cheese 🧀. Tested in production.",
  "Your fridge holds secrets beyond yogurt. This is fine 🔥.",
  "Unexpected nap is in your future 😴.",
  "The elevator will stop on every floor today. Good luck!",
  "Tomorrow’s bug will be today’s feature. Believe it.",
  "Today is a two-coffee kind of day ☕☕.",
  "You will debug in one try today. Consider yourself warned.",
  "StackOverflow is your second brain. Good luck!",
  "Your code is bug-free… until QA sees it. Today only.",
  "A cat will walk across your keyboard 🐈. Try again later.",
  "Your fridge holds secrets beyond yogurt. Try again later.",
  "You will laugh at your own joke today. Try again later.",
  "Naming things will haunt you forever. This is fine 🔥.",
  "Someone will say 'Let's circle back' in a meeting. Consider yourself warned.",
  "StackOverflow is your second brain. Tested in production.",
  "Your next commit message will be 'fix stuff'. Believe it.",
  "The elevator will stop on every floor today. This is fine 🔥.",
  "Tomorrow’s bug will be today’s feature. Today only.",
  "Your code is bug-free… until QA sees it. Consider yourself warned.",
  "You will dream in binary tonight. Today only.",
  "You will find fries at the bottom of the bag 🍟. Today only.",
  "Your fridge holds secrets beyond yogurt. Good luck!",
  "Your pizza will arrive with extra cheese 🧀. Consider yourself warned.",
  "Your phone battery will die at the worst moment 📱.",
  "Your socks will go missing mysteriously 🧦. Consider yourself warned.",
  "Your socks will go missing mysteriously 🧦. Believe it.",
  "Console.log is your spirit animal. Try again later.",
  "The stars say 'try turning it off and on again'.",
  "Deploy on Friday, what could go wrong? Today only.",
  "A potato will inspire your next idea 🥔. Try again later.",
  "Your pizza will arrive with extra cheese 🧀. Good luck!",
  "Your next commit message will be 'fix stuff'. Good luck!",
  "Unexpected nap is in your future 😴. Tested in production.",
  "404 fortune not found. This is fine 🔥.",
  "Unexpected nap is in your future 😴. Good luck!",
  "Console.log is your spirit animal.",
  "Git will ask you to resolve 100 conflicts today. Tested in production.",
  "You will dream in binary tonight. Try again later.",
  "A potato will inspire your next idea 🥔. Today only.",
  "Today is a two-coffee kind of day ☕☕. Tested in production.",
  "The weather will betray your outfit choice. Tested in production.",
  "You will dream in binary tonight.",
  "You will debug in one try today. Tested in production.",
  "Tomorrow’s bug will be today’s feature. Good luck!",
  "A potato will inspire your next idea 🥔. Consider yourself warned.",
  "Unexpected nap is in your future 😴. Believe it.",
  "Your fridge holds secrets beyond yogurt. Tested in production.",
  "A cat will walk across your keyboard 🐈. Today only.",
  "404 fortune not found. Believe it.",
  "Unexpected nap is in your future 😴. Try again later.",
  "The stars say 'try turning it off and on again'. Tested in production.",
  "Your code is bug-free… until QA sees it. This is fine 🔥.",
  "The universe approves your snack choice.",
  "Your pizza will arrive with extra cheese 🧀. Try again later.",
  "Your code is bug-free… until QA sees it. Tested in production.",
  "WiFi will betray you when you need it most. Believe it.",
  "Git will ask you to resolve 100 conflicts today. Believe it.",
  "WiFi will betray you when you need it most. Today only.",
  "You will find fries at the bottom of the bag 🍟. Believe it.",
  "Aliens are debugging the universe 👽. Believe it.",
  "Tomorrow’s bug will be today’s feature. Tested in production.",
  "You will dream in binary tonight. Tested in production.",
  "You will meet someone who asks 'So what do you do?' Consider yourself warned.",
  "Naming things will haunt you forever. Tested in production.",
  "Your socks will go missing mysteriously 🧦. Good luck!",
  "Your phone battery will die at the worst moment 📱. Good luck!",
  "The universe approves your snack choice. Consider yourself warned.",
  "Your phone battery will die at the worst moment 📱. Consider yourself warned.",
  "Deploy on Friday, what could go wrong? Try again later.",
  "The universe approves your snack choice. Good luck!",
  "You will find fries at the bottom of the bag 🍟. Try again later.",
  "Git will ask you to resolve 100 conflicts today. Today only.",
  "Today is a two-coffee kind of day ☕☕. Consider yourself warned.",
  "You will dream in binary tonight. Believe it.",
  "A potato will inspire your next idea 🥔. Believe it.",
  "Console.log is your spirit animal. Today only.",
  "You will debug in one try today. Believe it.",
  "You will find fries at the bottom of the bag 🍟. This is fine 🔥.",
  "The stars say 'try turning it off and on again'. Consider yourself warned.",
  "A cat will walk across your keyboard 🐈. Good luck!",
  "Deploy on Friday, what could go wrong? This is fine 🔥.",
  "Deploy on Friday, what could go wrong? Tested in production.",
  "Your socks will go missing mysteriously 🧦. This is fine 🔥.",
  "Tomorrow’s bug will be today’s feature.",
  "Your fridge holds secrets beyond yogurt. Consider yourself warned.",
  "Your next commit message will be 'fix stuff'. Today only.",
  "You will laugh at your own joke today.",
  "You will laugh at your own joke today. This is fine 🔥.",
  "The stars say 'try turning it off and on again'. This is fine 🔥.",
  "StackOverflow is your second brain.",
  "Someone will say 'Let's circle back' in a meeting. Believe it.",
  "Aliens are debugging the universe 👽. Consider yourself warned.",
  "The elevator will stop on every floor today.",
  "Your phone battery will die at the worst moment 📱. Tested in production.",
  "Console.log is your spirit animal. Tested in production.",
  "404 fortune not found.",
  "The bug was a feature all along.",
  "404 fortune not found. Try again later.",
  "Naming things will haunt you forever.",
  "The weather will betray your outfit choice.",
  "The weather will betray your outfit choice. Consider yourself warned.",
  "Aliens are debugging the universe 👽. Today only.",
  "Someone will say 'Let's circle back' in a meeting. Tested in production.",
  "Your pizza will arrive with extra cheese 🧀. This is fine 🔥.",
  "Git will ask you to resolve 100 conflicts today. This is fine 🔥.",
  "Someone will say 'Let's circle back' in a meeting. This is fine 🔥.",
  "You will laugh at your own joke today. Good luck!",
  "You will meet someone who asks 'So what do you do?' This is fine 🔥.",
  "Git will ask you to resolve 100 conflicts today. Consider yourself warned.",
  "404 fortune not found. Consider yourself warned.",
  "Console.log is your spirit animal. Good luck!",
  "The weather will betray your outfit choice. Good luck!",
  "You will debug in one try today. Today only.",
  "A potato will inspire your next idea 🥔.",
  "Today is a two-coffee kind of day ☕☕. Good luck!",
  "You will meet someone who asks 'So what do you do?' Tested in production.",
  "Your phone battery will die at the worst moment 📱. Believe it.",
  "Git will ask you to resolve 100 conflicts today. Good luck!",
  "Your next commit message will be 'fix stuff'. Try again later.",
  "Aliens are debugging the universe 👽.",
  "Someone will say 'Let's circle back' in a meeting. Try again later.",
  "The bug was a feature all along. Believe it.",
  "You will laugh at your own joke today. Today only.",
  "You will dream in binary tonight. Good luck!",
  "The elevator will stop on every floor today. Try again later.",
  "Naming things will haunt you forever. Consider yourself warned.",
  "Aliens are debugging the universe 👽. Try again later.",
  "Your socks will go missing mysteriously 🧦.",
  "Console.log is your spirit animal. This is fine 🔥.",
  "Your pizza will arrive with extra cheese 🧀.",
  "Console.log is your spirit animal. Believe it.",
  "You will debug in one try today. Try again later.",
  "WiFi will betray you when you need it most. Consider yourself warned.",
  "StackOverflow is your second brain. Try again later.",
  "Someone will say 'Let's circle back' in a meeting. Good luck!",
  "Your next commit message will be 'fix stuff'. Consider yourself warned.",
  "Your socks will go missing mysteriously 🧦. Tested in production.",
  "You will find fries at the bottom of the bag 🍟.",
  "Deploy on Friday, what could go wrong?",
  "You will meet someone who asks 'So what do you do?' Good luck!",
  "The stars say 'try turning it off and on again'. Believe it.",
  "A potato will inspire your next idea 🥔. Tested in production.",
  "You will find fries at the bottom of the bag 🍟. Good luck!",
  "Unexpected nap is in your future 😴. Consider yourself warned.",
  "Your next commit message will be 'fix stuff'.",
  "Aliens are debugging the universe 👽. Good luck!",
  "Your phone battery will die at the worst moment 📱. This is fine 🔥.",
  "Your code is bug-free… until QA sees it. Believe it.",
  "The weather will betray your outfit choice. This is fine 🔥.",
  "You will laugh at your own joke today. Believe it.",
  "Unexpected nap is in your future 😴. This is fine 🔥.",
  "A cat will walk across your keyboard 🐈. This is fine 🔥.",
  "StackOverflow is your second brain. Today only.",
  "You will meet someone who asks 'So what do you do?' Believe it.",
  "Deploy on Friday, what could go wrong? Believe it.",
  "WiFi will betray you when you need it most. This is fine 🔥.",
  "Your pizza will arrive with extra cheese 🧀. Believe it.",
  "A cat will walk across your keyboard 🐈. Believe it.",
  "Your code is bug-free… until QA sees it. Good luck!",
  "The universe approves your snack choice. Today only.",
  "A potato will inspire your next idea 🥔. This is fine 🔥.",
  "You will find fries at the bottom of the bag 🍟. Consider yourself warned.",
  "The elevator will stop on every floor today. Tested in production.",
  "Your fridge holds secrets beyond yogurt. Believe it.",
  "WiFi will betray you when you need it most.",
  "The universe approves your snack choice. Tested in production.",
  "Your phone battery will die at the worst moment 📱. Try again later.",
  "The stars say 'try turning it off and on again'. Today only.",
  "A cat will walk across your keyboard 🐈. Consider yourself warned.",
  "Deploy on Friday, what could go wrong? Good luck!",
  "You will dream in binary tonight. This is fine 🔥.",
  "404 fortune not found. Good luck!",
  "Today is a two-coffee kind of day ☕☕. Believe it.",
  "404 fortune not found. Tested in production.",
  "Your socks will go missing mysteriously 🧦. Try again later.",
  "Today is a two-coffee kind of day ☕☕. Try again later.",
  "Your socks will go missing mysteriously 🧦. Today only.",
  "The elevator will stop on every floor today. Believe it.",
  "Aliens are debugging the universe 👽. This is fine 🔥.",
  "You will dream in binary tonight. Consider yourself warned.",
];